### ISSUE TITLE
Add option for blacklisting/whitelisting fields when exporting

### ISSUE THREAD

**Issue by fredrikekelund** [apostrophecms/apostrophe-pieces-export#2]
Great module! One thing that could be improved however is the ability to select which fields are included/excluded when exporting. I'm thinking that this could be implemented in one of two ways: 

1. add something like an `excludeFieldsOnExport` array to the module options. 
2. change the output logic to look at the properties of the records that have been retrieved rather than the schema. This means that we would support `delete`ing of properties in the `beforeExport` function.

My knee jerk reaction was that perhaps the first option would be better, but I'm coming around to the second, because it seems more flexible and wouldn't be dramatically difficult to implement. Any thoughts?

**Comment by bgantick** [comment]
Update: option for `omitFields` added.

**Comment by fredrikekelund** [comment]
Awesome, thanks! :+1:
